# -*- coding: utf-8 -*-

from __future__ import annotations

from .registry import get_handler
from ....operators.context import EmitContext

# Import operator modules to register handlers.
from . import add  # noqa: F401
from . import sum  # noqa: F401
from . import mean  # noqa: F401
from . import sub  # noqa: F401
from . import mul  # noqa: F401
from . import div  # noqa: F401
from . import mod  # noqa: F401
from . import bitshift  # noqa: F401
from . import quantize_linear  # noqa: F401
from . import dequantize_linear  # noqa: F401
from . import dynamic_quantize_linear  # noqa: F401
from . import abs  # noqa: F401
from . import neg  # noqa: F401
from . import exp  # noqa: F401
from . import sin  # noqa: F401
from . import cos  # noqa: F401
from . import tan  # noqa: F401
from . import asin  # noqa: F401
from . import acos  # noqa: F401
from . import atan  # noqa: F401
from . import sinh  # noqa: F401
from . import cosh  # noqa: F401
from . import asinh  # noqa: F401
from . import acosh  # noqa: F401
from . import atanh  # noqa: F401
from . import sign  # noqa: F401
from . import erf  # noqa: F401
from . import round  # noqa: F401
from . import log  # noqa: F401
from . import reciprocal  # noqa: F401
from . import sqrt  # noqa: F401
from . import pow  # noqa: F401
from . import floor  # noqa: F401
from . import ceil  # noqa: F401
from . import elu  # noqa: F401
from . import celu  # noqa: F401
from . import selu  # noqa: F401
from . import hardsigmoid  # noqa: F401
from . import softplus  # noqa: F401
from . import softsign  # noqa: F401
from . import max  # noqa: F401
from . import min  # noqa: F401
from . import argmax  # noqa: F401
from . import argmin  # noqa: F401
from . import relu  # noqa: F401
from . import leaky_relu  # noqa: F401
from . import sigmoid  # noqa: F401
from . import tanh  # noqa: F401
from . import clip  # noqa: F401
from . import matmul  # noqa: F401
from . import matmul_integer  # noqa: F401
from . import qlinear_matmul  # noqa: F401
from . import gemm  # noqa: F401
from . import softmax  # noqa: F401
from . import identity  # noqa: F401
from . import reshape  # noqa: F401
from . import shape  # noqa: F401
from . import size  # noqa: F401
from . import constant  # noqa: F401
from . import constant_of_shape  # noqa: F401
from . import cast  # noqa: F401
from . import gather  # noqa: F401
from . import gather_nd  # noqa: F401
from . import gather_elements  # noqa: F401
from . import reverse_sequence  # noqa: F401
from . import roi_align  # noqa: F401
from . import compress  # noqa: F401
from . import det  # noqa: F401
from . import prelu  # noqa: F401
from . import flatten  # noqa: F401
from . import conv  # noqa: F401
from . import conv_integer  # noqa: F401
from . import conv_transpose  # noqa: F401
from . import qlinear_conv  # noqa: F401
from . import maxpool  # noqa: F401
from . import averagepool  # noqa: F401
from . import global_average_pool  # noqa: F401
from . import global_max_pool  # noqa: F401
from . import global_lppool  # noqa: F401
from . import lppool  # noqa: F401
from . import batchnorm  # noqa: F401
from . import instance_normalization  # noqa: F401
from . import mean_variance_normalization  # noqa: F401
from . import lrn  # noqa: F401
from . import lp_normalization  # noqa: F401
from . import concat  # noqa: F401
from . import transpose  # noqa: F401
from . import pad  # noqa: F401
from . import slice  # noqa: F401
from . import expand  # noqa: F401
from . import where  # noqa: F401
from . import scatter_elements  # noqa: F401
from . import scatter_nd  # noqa: F401
from . import scatter  # noqa: F401
from . import onehot  # noqa: F401
from . import equal  # noqa: F401
from . import greater  # noqa: F401
from . import less  # noqa: F401
from . import greater_or_equal  # noqa: F401
from . import less_or_equal  # noqa: F401
from . import isinf  # noqa: F401
from . import isnan  # noqa: F401
from . import logical_not  # noqa: F401
from . import logical_and  # noqa: F401
from . import logical_or  # noqa: F401
from . import logical_xor  # noqa: F401
from . import reduce_mean  # noqa: F401
from . import reduce_sum  # noqa: F401
from . import reduce_max  # noqa: F401
from . import reduce_min  # noqa: F401
from . import reduce_prod  # noqa: F401
from . import reduce_l1  # noqa: F401
from . import reduce_l2  # noqa: F401
from . import reduce_sum_square  # noqa: F401
from . import reduce_log_sum  # noqa: F401
from . import reduce_log_sum_exp  # noqa: F401
from . import space_to_depth  # noqa: F401
from . import depth_to_space  # noqa: F401
from . import squeeze  # noqa: F401
from . import unsqueeze  # noqa: F401
from . import tile  # noqa: F401
from . import resize  # noqa: F401
from . import upsample  # noqa: F401
from . import dropout  # noqa: F401
from . import nonzero  # noqa: F401
from . import non_max_suppression  # noqa: F401
from . import hardmax  # noqa: F401
from . import logsoftmax  # noqa: F401
from . import range  # noqa: F401
from . import cumsum  # noqa: F401
from . import split  # noqa: F401
from . import topk  # noqa: F401
from . import einsum  # noqa: F401
from . import thresholded_relu  # noqa: F401
from . import shrink  # noqa: F401
from . import eyelike  # noqa: F401
from . import random_uniform  # noqa: F401
from . import random_uniform_like  # noqa: F401
from . import random_normal  # noqa: F401
from . import random_normal_like  # noqa: F401
from . import multinomial  # noqa: F401
from . import unique  # noqa: F401
from . import negative_log_likelihood_loss  # noqa: F401
from . import softmax_cross_entropy_loss  # noqa: F401
from . import max_roi_pool  # noqa: F401
from . import max_unpool  # noqa: F401
from . import rnn  # noqa: F401
from . import gru  # noqa: F401
from . import lstm  # noqa: F401
from . import if_op  # noqa: F401
from . import loop  # noqa: F401
from . import scan  # noqa: F401
from . import sequence_construct  # noqa: F401
from . import sequence_empty  # noqa: F401
from . import sequence_at  # noqa: F401
from . import sequence_insert  # noqa: F401
from . import sequence_erase  # noqa: F401
from . import sequence_length  # noqa: F401
from . import split_to_sequence  # noqa: F401
from . import concat_from_sequence  # noqa: F401
from . import string_normalizer  # noqa: F401
from . import tfidf_vectorizer  # noqa: F401

__all__ = ["get_handler", "EmitContext"]
