# -*- coding: utf-8 -*-

import os

from keil.config import get_include_path, get_sysroot_path, get_armgcc_extra_include, get_toolchain_path
from keil.device import detect_cpu_architecture
from keil2cmake_common import norm_path
from compiler.armgcc.layout import infer_gcc_internal_includes_from_armgcc_path


def generate_clangd_config(project_root: str, compiler_type: str, cpu_arch: str):
    """生成 .clangd 配置文件，根据编译器类型自动选择对应的头文件路径。"""

    system_include = ""
    sysroot = ""
    extra_include = ""
    armgcc_internal_includes: list[str] = []

    if compiler_type == 'armclang':
        system_include = norm_path(get_include_path('ARMCLANG'))
    elif compiler_type == 'armcc':
        system_include = norm_path(get_include_path('ARMCC'))
    elif compiler_type == 'armgcc':
        sysroot = norm_path(get_sysroot_path())
        extra_include = norm_path(get_armgcc_extra_include())
        armgcc_internal_includes = infer_gcc_internal_includes_from_armgcc_path(get_toolchain_path('ARMGCC'))

    arch_define = {
        'Cortex-M0': '__ARM_ARCH_6M__',
        'Cortex-M3': '__ARM_ARCH_7M__',
        'Cortex-M4': '__ARM_ARCH_7EM__',
        'Cortex-M7': '__ARM_ARCH_7EM__',
        'Cortex-M33': '__ARM_ARCH_8M_MAIN__',
    }.get(cpu_arch, '__ARM_ARCH_7M__')

    add_flags = [
        '--target=arm-arm-none-eabi',
        '-D__ARM_ARCH_PROFILE="M"',
    ]

    if compiler_type == 'armgcc' and sysroot:
        add_flags.append('--sysroot=' + sysroot)
        sysroot_include = norm_path(os.path.join(sysroot, 'include'))
        if sysroot_include:
            add_flags.extend(['-isystem', sysroot_include])

    if system_include:
        add_flags.extend(['-isystem', system_include])
    if extra_include:
        add_flags.extend(['-isystem', extra_include])

    if compiler_type == 'armgcc':
        for inc in armgcc_internal_includes:
            add_flags.extend(['-isystem', inc])

    add_flags.extend([
        f'-D{arch_define}',
        '-D__MICROLIB',
        '-DUSE_STDPERIPH_DRIVER',
        '-DSTM32F10X_HD',
        '-D__NO_EMBEDDED_ASM',
        '-fms-extensions',
    ])

    add_flags_yaml = ",\n    ".join(f'"{x}"' for x in add_flags)

    # 根据编译器类型自动设置 compile_commands.json 路径
    compilation_db_path = f'build/{compiler_type}'

    clangd_content = f'''# clangd config generated by Keil2Cmake
# 根据编译器类型自动配置: {compiler_type}

CompilationDatabase: {compilation_db_path}

CompileFlags:
  Remove: [
    -mcpu=*,
    -mthumb*,
    -mfloat-abi=*,
    -mfpu=*,
    -ffunction-sections,
    -fdata-sections,
    -g,
    -O*,
    -std=*,
    -W*,
    --cpu=*,
    --apcs=*,
    --split_sections,
    --debug,
    --cpp,
    --strict,
    -D__CC_ARM
  ]

  Add: [
        {add_flags_yaml}
  ]

Diagnostics:
  Suppress: [
    unknown-warning-option,
    invalid_token_after_toplevel_declarator,
    option_ignored,
    unused-command-line-argument,
    pp_file_not_found
  ]

Index:
  Background: Build
  StandardLibrary: false
'''

    with open(os.path.join(project_root, '.clangd'), 'w', encoding='utf-8') as f:
        f.write(clangd_content)
