# -*- coding: utf-8 -*-

import os

from keil2cmake_common import ensure_dir


def generate_scatter_file(destination: str) -> None:
    """生成默认的 scatter 文件。"""
    ensure_dir(destination)
    template_scatter = '''
; *************************************************************
; *** Scatter-Loading Description File generated by uVision ***
; *************************************************************

LR_IROM1 0x08000000 0x00100000  {    ; load region size_region
  ER_IROM1 0x08000000 0x00100000  {  ; load address = execution address
   *.o (RESET, +First)
   *(InRoot$$Sections)
   .ANY (+RO)
   .ANY (+XO)
  }
  RW_IRAM1 0x20000000 0x00020000  {  ; RW data
   .ANY (+RW +ZI)
  }
}
'''
    out_path = os.path.join(destination, 'Template.sct')
    if not os.path.exists(out_path):
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(template_scatter.strip())


def generate_gcc_linker_script(destination: str) -> None:
    """生成默认 GCC linker script（需要用户根据芯片修改内存大小）。"""
    ensure_dir(destination)
    template_ld = r'''
/* Auto-generated template for arm-none-eabi-gcc.
 * NOTE: You MUST adjust MEMORY sizes to your MCU.
 */

ENTRY(Reset_Handler)

MEMORY
{
    FLASH (rx)  : ORIGIN = 0x08000000, LENGTH = 1024K
    RAM   (rwx) : ORIGIN = 0x20000000, LENGTH = 128K
}

SECTIONS
{
    .isr_vector :
    {
        KEEP(*(.isr_vector))
    } > FLASH

    .text :
    {
        *(.text*)
        *(.rodata*)
        KEEP(*(.init))
        KEEP(*(.fini))
    } > FLASH

    .ARM.extab : { *(.ARM.extab* .gnu.linkonce.armextab.*) } > FLASH
    .ARM.exidx :
    {
        __exidx_start = .;
        *(.ARM.exidx* .gnu.linkonce.armexidx.*)
        __exidx_end = .;
    } > FLASH

    .data : AT (ADDR(.text) + SIZEOF(.text))
    {
        __data_start__ = .;
        *(.data*)
        __data_end__ = .;
    } > RAM

    .bss :
    {
        __bss_start__ = .;
        *(.bss*)
        *(COMMON)
        __bss_end__ = .;
    } > RAM
}
'''
    out_path = os.path.join(destination, 'Template.ld')
    if not os.path.exists(out_path):
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(template_ld.strip())
