# -*- coding: utf-8 -*-

import os

from keil.config import get_toolchain_path, get_include_path, get_sysroot_path, get_armgcc_extra_include
from keil.device import detect_cpu_architecture, get_arm_arch_for_clang, get_compiler_cpu_name
from keil2cmake_common import ensure_dir, norm_path
from i18n import t


def generate_toolchains(project_data: dict, project_root: str) -> None:
    """Generate a single toolchain file under cmake/internal/toolchain.cmake.

    The selected compiler is controlled by cache variable K2C_COMPILER (armcc/armclang/armgcc),
    typically set via CMakePresets.json.
    """
    cpu_arch = detect_cpu_architecture(project_data['device'])
    arm_arch = get_arm_arch_for_clang(cpu_arch)
    cpu_name = get_compiler_cpu_name(cpu_arch)

    armclang_path = get_toolchain_path('ARMCLANG')
    armcc_path = get_toolchain_path('ARMCC')
    armgcc_path = get_toolchain_path('ARMGCC')

    armcc_include = get_include_path('ARMCC')
    armclang_include = get_include_path('ARMCLANG')
    armgcc_sysroot = get_sysroot_path()
    armgcc_extra_include = get_armgcc_extra_include()

    internal_dir = os.path.join(project_root, 'cmake', 'internal')
    ensure_dir(internal_dir)

    user_rel = "${CMAKE_CURRENT_LIST_DIR}/../user/keil2cmake_user.cmake"

    scatter_template = r'''
; *************************************************************
; *** Scatter-Loading Description File generated by uVision ***
; *************************************************************

LR_IROM1 0x08000000 0x00100000  {    ; load region size_region
  ER_IROM1 0x08000000 0x00100000  {  ; load address = execution address
   *.o (RESET, +First)
   *(InRoot$$Sections)
   .ANY (+RO)
   .ANY (+XO)
  }
  RW_IRAM1 0x20000000 0x00020000  {  ; RW data
   .ANY (+RW +ZI)
  }
}
'''.strip()

    ld_template = r'''
/* Auto-generated template for arm-none-eabi-gcc.
 * NOTE: You MUST adjust MEMORY sizes to your MCU.
 */

ENTRY(Reset_Handler)

MEMORY
{
    FLASH (rx)  : ORIGIN = 0x08000000, LENGTH = 1024K
    RAM   (rwx) : ORIGIN = 0x20000000, LENGTH = 128K
}

SECTIONS
{
    .isr_vector :
    {
        KEEP(*(.isr_vector))
    } > FLASH

    .text :
    {
        *(.text*)
        *(.rodata*)
        KEEP(*(.init))
        KEEP(*(.fini))
    } > FLASH

    .ARM.extab : { *(.ARM.extab* .gnu.linkonce.armextab.*) } > FLASH
    .ARM.exidx :
    {
        __exidx_start = .;
        *(.ARM.exidx* .gnu.linkonce.armexidx.*)
        __exidx_end = .;
    } > FLASH

    .data : AT (ADDR(.text) + SIZEOF(.text))
    {
        __data_start__ = .;
        *(.data*)
        __data_end__ = .;
    } > RAM

    .bss :
    {
        __bss_start__ = .;
        *(.bss*)
        *(COMMON)
        __bss_end__ = .;
    } > RAM
}
'''.strip()

    default_sct_path = os.path.join(internal_dir, 'keil2cmake_default.sct')
    if not os.path.exists(default_sct_path):
        with open(default_sct_path, 'w', encoding='utf-8-sig') as f:
            f.write(scatter_template)

    default_ld_path = os.path.join(internal_dir, 'keil2cmake_default.ld')
    if not os.path.exists(default_ld_path):
        with open(default_ld_path, 'w', encoding='utf-8-sig') as f:
            f.write(ld_template)

    content = f'''{t('gen.toolchain.header.title')}

cmake_minimum_required(VERSION 3.20)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR {cpu_name})
set(CMAKE_SYSTEM_ARCH {arm_arch})

{t('gen.toolchain.select_compiler')}
if(NOT DEFINED K2C_COMPILER OR K2C_COMPILER STREQUAL "")
    set(K2C_COMPILER "armcc" CACHE STRING "Compiler" FORCE)
endif()

if(EXISTS "{user_rel}")
    include("{user_rel}")
endif()

set(ARMCC_BIN "{norm_path(armcc_path)}")
set(ARMCLANG_BIN "{norm_path(armclang_path)}")
set(ARMGCC_BIN "{norm_path(armgcc_path)}")

set(K2C_ARMCC_INCLUDE "{norm_path(armcc_include)}")
set(K2C_ARMCLANG_INCLUDE "{norm_path(armclang_include)}")
set(K2C_ARMGCC_SYSROOT "{norm_path(armgcc_sysroot)}")
set(K2C_ARMGCC_INCLUDE "{norm_path(armgcc_extra_include)}")

{t('gen.toolchain.linker_scripts')}
if(K2C_COMPILER STREQUAL "armcc" OR K2C_COMPILER STREQUAL "armclang")
    if(K2C_LINKER_SCRIPT_SCT STREQUAL "")
        set(K2C_LINKER_SCRIPT_SCT "${{CMAKE_CURRENT_LIST_DIR}}/keil2cmake_default.sct" CACHE FILEPATH "Scatter file for armcc/armclang" FORCE)
    endif()
elseif(K2C_COMPILER STREQUAL "armgcc")
    if(K2C_LINKER_SCRIPT_LD STREQUAL "")
        set(K2C_LINKER_SCRIPT_LD "${{CMAKE_CURRENT_LIST_DIR}}/keil2cmake_default.ld" CACHE FILEPATH "Linker script for armgcc" FORCE)
    endif()
endif()

if(K2C_COMPILER STREQUAL "armclang")
    set(CMAKE_C_COMPILER   "${{ARMCLANG_BIN}}/armclang.exe")
    set(CMAKE_CXX_COMPILER "${{ARMCLANG_BIN}}/armclang.exe")
    set(CMAKE_ASM_COMPILER "${{ARMCLANG_BIN}}/armclang.exe")
    set(CMAKE_LINKER       "${{ARMCLANG_BIN}}/armlink.exe")
    set(CMAKE_AR           "${{ARMCLANG_BIN}}/armar.exe")
    set(CMAKE_FROMELF      "${{ARMCLANG_BIN}}/fromelf.exe")

    set(_K2C_COMMON_FLAGS "--target=arm-arm-none-eabi -mcpu={cpu_name} -mthumb")
    set(CMAKE_C_FLAGS_INIT   "${{_K2C_COMMON_FLAGS}} -ffunction-sections -fdata-sections")
    set(CMAKE_CXX_FLAGS_INIT "${{_K2C_COMMON_FLAGS}} -ffunction-sections -fdata-sections")
    set(CMAKE_ASM_FLAGS_INIT "${{_K2C_COMMON_FLAGS}}")
elseif(K2C_COMPILER STREQUAL "armcc")
    set(CMAKE_C_COMPILER   "${{ARMCC_BIN}}/armcc.exe")
    set(CMAKE_CXX_COMPILER "${{ARMCC_BIN}}/armcc.exe")
    set(CMAKE_ASM_COMPILER "${{ARMCC_BIN}}/armasm.exe")
    set(CMAKE_LINKER       "${{ARMCC_BIN}}/armlink.exe")
    set(CMAKE_AR           "${{ARMCC_BIN}}/armar.exe")
    set(CMAKE_FROMELF      "${{ARMCC_BIN}}/fromelf.exe")

    set(_K2C_COMMON_FLAGS "--cpu={cpu_arch} --apcs=interwork")
    set(CMAKE_C_FLAGS_INIT   "${{_K2C_COMMON_FLAGS}} --c99 --split_sections")
    set(CMAKE_CXX_FLAGS_INIT "${{_K2C_COMMON_FLAGS}} --cpp --split_sections")
    set(CMAKE_ASM_FLAGS_INIT "${{_K2C_COMMON_FLAGS}}")
elseif(K2C_COMPILER STREQUAL "armgcc")
    set(CMAKE_C_COMPILER   "${{ARMGCC_BIN}}/arm-none-eabi-gcc.exe")
    set(CMAKE_CXX_COMPILER "${{ARMGCC_BIN}}/arm-none-eabi-g++.exe")
    set(CMAKE_ASM_COMPILER "${{ARMGCC_BIN}}/arm-none-eabi-gcc.exe")
    set(CMAKE_AR           "${{ARMGCC_BIN}}/arm-none-eabi-ar.exe")
    set(CMAKE_OBJCOPY      "${{ARMGCC_BIN}}/arm-none-eabi-objcopy.exe")
    set(CMAKE_SIZE         "${{ARMGCC_BIN}}/arm-none-eabi-size.exe")

    set(_K2C_COMMON_FLAGS "-mcpu={cpu_name} -mthumb -ffunction-sections -fdata-sections")
    if(NOT K2C_ARMGCC_SYSROOT STREQUAL "")
        set(_K2C_COMMON_FLAGS "${{_K2C_COMMON_FLAGS}} --sysroot=${{K2C_ARMGCC_SYSROOT}}")
    endif()
    set(CMAKE_C_FLAGS_INIT   "${{_K2C_COMMON_FLAGS}}")
    set(CMAKE_CXX_FLAGS_INIT "${{_K2C_COMMON_FLAGS}}")
    set(CMAKE_ASM_FLAGS_INIT "${{_K2C_COMMON_FLAGS}}")
else()
    message(FATAL_ERROR "Unsupported K2C_COMPILER: '${{K2C_COMPILER}}'")
endif()

set(CMAKE_C_COMPILER_WORKS 1 CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_WORKS 1 CACHE INTERNAL "")
set(CMAKE_ASM_COMPILER_WORKS 1 CACHE INTERNAL "")
set(CMAKE_C_COMPILER_FORCED TRUE CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_FORCED TRUE CACHE INTERNAL "")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
'''

    with open(os.path.join(internal_dir, 'toolchain.cmake'), 'w', encoding='utf-8-sig') as f:
        f.write(content)
